### ISSUE TITLE
missing H3 functions toparent?

### ISSUE THREAD

**Issue by Almandeen** [davidfauth/Neo4jH3#11]
Dear David,

After building the package with Maven (version 5.12), and moving it to the plugins folder of a project (version 5.12 and 5.13), I am able to see most of the H3 functions in the procedures list from Neo4j browser, but unable to call com.neo4jh3.toparent and com.neo4jh3.toparentString though they are described in the documentation?

I also installed the plugin using both the 5.12 and 5.13 -jar files directly from the Release page as well to see if the problem was in the building of the package. I am on a windows 11 computer, and not a Java developer so I am not sure exactly where the bug might arise.
If it is on my end, I am sorry for any inconvenience but I thought I would mention it if others had the same experience.

Thank your hard work in bringing H3 to Neo4j.
Best regards
Marie

**Comment by davidfauth** [comment]
Marie,

Let me look into this and see what might be happening.

Dave

**Comment by davidfauth** [comment]
Marie,

What is the output of this command:

RETURN com.neo4jh3.toparent(604197150066212863, 3) AS value


Dave

**Comment by Almandeen** [comment]
Hi Dave

RETURN com.neo4jh3.toparent(604197150066212863, 3) AS value
590686371182542847

But for CALL com.neo4jh3.toparent(604197150066212863, 3), I get.
"There is no procedure with the name `com.neo4jh3.toparent` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed."

Likewise, CALL com.neo4jh3.tochildren(604197150066212863, 7) returns:
│608700749576142847│
├──────────────────┤
│608700749592920063│
├──────────────────┤
│608700749609697279│
├──────────────────┤
│608700749626474495│
├──────────────────┤
│608700749643251711│
├──────────────────┤
│608700749660028927│
├──────────────────┤
│608700749676806143│

But, RETURN com.neo4jh3.tochildren(604197150066212863, 7) results in this.
"Unknown function 'com.neo4jh3.tochildren' (line 1, column 8 (offset: 7))
"EXPLAIN RETURN com.neo4jh3.tochildren(604197150066212863, 7)""

So some of the functions are procedures and some are functions? 
I think that's why I got confused, sorry for the inconvenience.

Cheers
Marie
